"""initial schema

Baseline migration matching the schema previously created by
Base.metadata.create_all() through Sprint 6 — users, locations, reports
(incl. verification_status), observations, verification_events. Generated
via `alembic revision --autogenerate` against a scratch DB and verified
with `alembic upgrade head` / `alembic downgrade base`.

IMPORTANT for existing deployments: if a database already has these tables
(created via the old create_all() path), do NOT run this migration against
it — it will try to create tables that already exist. Instead run
`alembic stamp head` to mark the DB as already at this revision without
re-running the DDL. Fresh databases should just run `alembic upgrade head`.

Revision ID: e829fbc64e49
Revises: 
Create Date: 2026-08-29 10:16:03.132117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e829fbc64e49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('stream_name', sa.String(length=200), nullable=True),
    sa.Column('stream_segment', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'ANALYZING', 'ANALYZED', 'UNDER_REVIEW', 'VERIFIED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('algae_indicator', sa.String(length=50), nullable=True),
    sa.Column('color_anomaly', sa.String(length=50), nullable=True),
    sa.Column('visible_waste', sa.Boolean(), nullable=True),
    sa.Column('turbidity_indicator', sa.String(length=50), nullable=True),
    sa.Column('image_quality', sa.String(length=50), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('verification_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verifier_reference', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_events_report_id'), 'verification_events', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_events_report_id'), table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_table('observations')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
